spring:
  h2:
    console:
      enabled: true
      path: /h2
    settings.trace: false
  datasource:
    url: jdbc:h2:file:./db
    driver-calss-name: org.h2.Driver
bot:
  name: ${BOT_NAME}
  api-key: ${BOT_API_KEY}
